#!/usr/bin/env python3
"""Compile a Lua source file to one 32-bit luac chunk and emit it as a C header.

The bytecode-only firmware (#128) has no on-device parser, so its resident boot
chunk must ship precompiled. This bakes lua/boot/boot.lua into
firmware/gen/boot_lc.h (a `static const unsigned char boot_lc[]`), which main.c
loads with luaL_loadbuffer at startup - `sizeof boot_lc` is the chunk length.

Compilation goes through the same host luac Docker image as replpipe.py, built
from the vendored lua/ tree + LUA_32BITS luaconf.h, so the chunk header matches
what the device's lundump.c accepts. Whole file = one chunk (unlike replpipe's
per-line REPL framing). Python stdlib only.
"""
import argparse
import os
import subprocess
import sys


def luac_compile(src: bytes, image: str) -> bytes:
    """Compile `src` to a stripped bytecode chunk via the luac Docker image.

    Source rides stdin, the chunk rides stdout (`-o /dev/stdout -`), so no bind
    mounts and no host paths leak into the container.
    """
    try:
        proc = subprocess.run(
            ["docker", "run", "--rm", "-i", image,
             "-s", "-o", "/dev/stdout", "-"],
            input=src, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
        )
    except FileNotFoundError:
        sys.exit("embed: docker not found on PATH")
    if proc.returncode != 0:
        sys.exit("embed: luac failed:\n" + proc.stderr.decode("utf-8", "replace"))
    return proc.stdout


def emit_header(out, name: str, chunk: bytes, src: str) -> None:
    """Write the chunk as a C byte-array header (12 bytes per row)."""
    out.write(f"/* Generated by tools/luac/embed.py from {src}.\n"
              " * Do not edit; regenerated on every `task lua:firmware:build`. */\n")
    out.write(f"static const unsigned char {name}[] = {{\n")
    for i in range(0, len(chunk), 12):
        row = ", ".join(f"0x{b:02x}" for b in chunk[i:i + 12])
        out.write(f"  {row},\n")
    out.write("};\n")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("input", help="Lua source file to compile and embed")
    ap.add_argument("-o", "--output", help="header path (default: stdout)")
    ap.add_argument("--name", default="boot_lc",
                    help="C array name (default: boot_lc)")
    ap.add_argument("--image", default="nabaztag-sdk-luac",
                    help="luac Docker image (default: nabaztag-sdk-luac)")
    args = ap.parse_args()

    with open(args.input, "rb") as f:
        chunk = luac_compile(f.read(), args.image)

    src = os.path.basename(args.input)
    out = open(args.output, "w") if args.output else sys.stdout
    try:
        emit_header(out, args.name, chunk, src)
    finally:
        if args.output:
            out.close()
    return 0


if __name__ == "__main__":
    sys.exit(main())
